{{- if or .Values.postgresql.enabled .Values.rabbitmq.enabled .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "cloudsound.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | default "local-dev-secret-key" | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  minio-secret-key: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.facebookAccessToken }}
  facebook-access-token: {{ .Values.secrets.facebookAccessToken | quote }}
  {{- end }}
{{- end }}

