apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: cloudsound
      meta.helm.sh/release-namespace: cloudsound
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000001
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 10.1.5
      helm.sh/chart: grafana-7.0.0
    name: cloudsound-grafana
    namespace: cloudsound
    resourceVersion: "14650"
    uid: ca6dd5d1-2ae5-44a0-b475-fca310877267
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-ca6dd5d1-2ae5-44a0-b475-fca310877267
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: cloudsound
      meta.helm.sh/release-namespace: cloudsound
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000001
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus
      app.kubernetes.io/version: v2.47.0
      helm.sh/chart: prometheus-25.0.0
    name: cloudsound-prometheus-server
    namespace: cloudsound
    resourceVersion: "14655"
    uid: f2c78681-ee24-4e15-950c-0b69ccf543c2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-f2c78681-ee24-4e15-950c-0b69ccf543c2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-cloudsound-kafka-controller-0
    namespace: cloudsound
    resourceVersion: "14718"
    uid: de4bb6ba-c303-4c6b-ac01-bb64b2c8f4c9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-de4bb6ba-c303-4c6b-ac01-bb64b2c8f4c9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-cloudsound-kafka-controller-1
    namespace: cloudsound
    resourceVersion: "14751"
    uid: b2adbeb7-e2f2-44bd-ba9a-a3bc3027efd2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-b2adbeb7-e2f2-44bd-ba9a-a3bc3027efd2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000001
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: controller-eligible
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: kafka
    name: data-cloudsound-kafka-controller-2
    namespace: cloudsound
    resourceVersion: "14732"
    uid: b6b05087-9b2e-4ac6-a6c1-70d4eb02fba6
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-b6b05087-9b2e-4ac6-a6c1-70d4eb02fba6
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: rabbitmq
    name: data-cloudsound-rabbitmq-0
    namespace: cloudsound
    resourceVersion: "14795"
    uid: bb3c0aa8-82be-4ce9-880e-e0b2673805d9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: managed-premium
    volumeMode: Filesystem
    volumeName: pvc-bb3c0aa8-82be-4ce9-880e-e0b2673805d9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000001
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: read
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-read-0
    namespace: cloudsound
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: loki-read
      uid: d13ee071-1e28-4a79-8e4d-0fc7e0aaed95
    resourceVersion: "14762"
    uid: 8c0b86e1-dc5e-482a-996c-954d0d70554f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-8c0b86e1-dc5e-482a-996c-954d0d70554f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: read
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-read-1
    namespace: cloudsound
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: loki-read
      uid: d13ee071-1e28-4a79-8e4d-0fc7e0aaed95
    resourceVersion: "14772"
    uid: ad8406c4-40f1-4b6f-95a3-eddeaeeddd9a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: read
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-read-2
    namespace: cloudsound
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: loki-read
      uid: d13ee071-1e28-4a79-8e4d-0fc7e0aaed95
    resourceVersion: "14764"
    uid: fd1dbb59-cb4d-4750-8a46-61a70e561f6d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-write-0
    namespace: cloudsound
    resourceVersion: "14755"
    uid: 3939ffb5-7473-440c-967b-f0af692373a6
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-3939ffb5-7473-440c-967b-f0af692373a6
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-write-1
    namespace: cloudsound
    resourceVersion: "14638"
    uid: a455c1cf-6cff-428a-8183-70cfac8ef393
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-14810409-vmss000001
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: cloudsound
      app.kubernetes.io/name: loki
    name: data-loki-write-2
    namespace: cloudsound
    resourceVersion: "19937"
    uid: 70ef1db4-b99c-4d01-80af-11edc72c868d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-70ef1db4-b99c-4d01-80af-11edc72c868d
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2026-01-09T16:11:04Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgres
    name: postgres-data-cloudsound-postgres-0
    namespace: cloudsound
    resourceVersion: "14670"
    uid: ef4af06d-383d-4361-a90c-dd32e6dd0946
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
