apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudsound
type: Opaque
stringData:
  password: "cloudsound_dev"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: cloudsound
type: Opaque
stringData:
  password: "cloudsound_dev"

