#!/bin/bash

# Initial Azure setup script for CloudSound
# This script helps you set up your Azure environment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}CloudSound Azure Setup${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed${NC}"
    echo "Please install it from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if user is logged in
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Logging in...${NC}"
    az login
fi

# Show current subscription
echo -e "${GREEN}Current Azure subscription:${NC}"
az account show --output table

# Ask if user wants to change subscription
read -p "Do you want to change subscription? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    az account list --output table
    read -p "Enter subscription ID: " SUB_ID
    az account set --subscription "$SUB_ID"
    echo -e "${GREEN}Subscription changed${NC}"
fi

# Set default values
RESOURCE_GROUP=${RESOURCE_GROUP:-"cloudsound-rg"}
LOCATION=${LOCATION:-"eastus"}

echo -e "\n${YELLOW}Configuration:${NC}"
echo "Resource Group: $RESOURCE_GROUP"
echo "Location: $LOCATION"
echo

read -p "Continue with these settings? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter resource group name: " RESOURCE_GROUP
    read -p "Enter location (e.g., eastus): " LOCATION
fi

# Create resource group
echo -e "\n${YELLOW}Creating resource group...${NC}"
az group create \
    --name "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --output table

# Register resource providers
echo -e "\n${YELLOW}Registering resource providers...${NC}"
PROVIDERS=(
    "Microsoft.ContainerService"
    "Microsoft.Storage"
    "Microsoft.Network"
    "Microsoft.Compute"
    "Microsoft.DBforPostgreSQL"
    "Microsoft.OperationalInsights"
)

for provider in "${PROVIDERS[@]}"; do
    echo "Registering $provider..."
    az provider register --namespace "$provider" --wait
done

echo -e "${GREEN}All providers registered${NC}"

# Export variables for Terraform
echo -e "\n${YELLOW}Setting up Terraform variables...${NC}"

cat > infrastructure/terraform/terraform.tfvars <<EOF
# CloudSound Azure Configuration
# Auto-generated by azure-setup.sh

resource_group_name = "$RESOURCE_GROUP"
location            = "$LOCATION"
project_name        = "cloudsound"
environment         = "production"

# AKS Configuration
aks_node_count     = 2
aks_node_size      = "Standard_B2s"

# PostgreSQL Configuration
postgres_admin_user = "cloudsoundadmin"
postgres_sku_name   = "B_Standard_B1ms"
postgres_storage_mb = 32768

# Enter your email for SSL certificates
admin_email = "your-email@example.com"
EOF

echo -e "${GREEN}Terraform variables file created at infrastructure/terraform/terraform.tfvars${NC}"
echo -e "${YELLOW}Please edit this file and add your email address${NC}"

# Create service principal for GitHub Actions
echo -e "\n${YELLOW}Creating service principal for GitHub Actions...${NC}"
read -p "Do you want to create a service principal for CI/CD? (y/n): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    SUBSCRIPTION_ID=$(az account show --query id -o tsv)
    
    echo "Creating service principal..."
    SP_OUTPUT=$(az ad sp create-for-rbac \
        --name "github-actions-cloudsound" \
        --role contributor \
        --scopes "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP" \
        --sdk-auth)
    
    echo -e "\n${GREEN}Service Principal created!${NC}"
    echo -e "${YELLOW}Add this as AZURE_CREDENTIALS secret in GitHub:${NC}\n"
    echo "$SP_OUTPUT"
    echo -e "\n${YELLOW}Save this output - you'll need it for GitHub Actions${NC}"
fi

# Summary
echo -e "\n${BLUE}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}\n"

echo -e "Next steps:"
echo -e "1. ${YELLOW}Edit infrastructure/terraform/terraform.tfvars${NC} with your email"
echo -e "2. ${YELLOW}Deploy infrastructure:${NC} cd infrastructure/terraform && terraform apply"
echo -e "3. ${YELLOW}Configure GitHub secrets:${NC} Add AZURE_CREDENTIALS, ACR credentials, etc."
echo -e "4. ${YELLOW}Build and push images:${NC} ./scripts/build-and-push-azure.sh"
echo -e "5. ${YELLOW}Deploy application:${NC} cd infrastructure/helm/cloudsound && helm install..."

echo -e "\n${GREEN}See docs/AZURE_DEPLOYMENT.md for detailed instructions${NC}\n"

