#!/bin/bash

# Initial Azure setup script for CloudSound
# This script helps you set up your Azure environment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}CloudSound Azure Setup${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed${NC}"
    echo "Please install it from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if user is logged in
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Logging in...${NC}"
    # Use device code flow if running as root or if DISPLAY is not available
    if [ "$EUID" -eq 0 ] || [ -z "$DISPLAY" ]; then
        echo -e "${YELLOW}Using device code flow (no browser available)${NC}"
        az login --use-device-code
    else
        # Try browser login, fall back to device code if it fails
        if ! az login 2>/dev/null; then
            echo -e "${YELLOW}Browser login failed, using device code flow...${NC}"
            az login --use-device-code
        fi
    fi
fi

# Show current subscription
echo -e "${GREEN}Current Azure subscription:${NC}"
az account show --output table

# Ask if user wants to change subscription
read -p "Do you want to change subscription? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    az account list --output table
    read -p "Enter subscription ID: " SUB_ID
    az account set --subscription "$SUB_ID"
    echo -e "${GREEN}Subscription changed${NC}"
fi

# Set default values
RESOURCE_GROUP=${RESOURCE_GROUP:-"cloudsound-rg"}
LOCATION=${LOCATION:-"eastus"}

echo -e "\n${YELLOW}Configuration:${NC}"
echo "Resource Group: $RESOURCE_GROUP"
echo "Location: $LOCATION"
echo

read -p "Continue with these settings? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter resource group name: " RESOURCE_GROUP
    read -p "Enter location (e.g., eastus): " LOCATION
fi

# Create resource group (or use existing)
echo -e "\n${YELLOW}Checking resource group...${NC}"
if az group show --name "$RESOURCE_GROUP" &> /dev/null; then
    echo -e "${GREEN}Resource group '$RESOURCE_GROUP' already exists${NC}"
    az group show --name "$RESOURCE_GROUP" --output table
else
    echo -e "${YELLOW}Creating resource group...${NC}"
    az group create \
        --name "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --output table
fi

# Register resource providers
echo -e "\n${YELLOW}Checking resource providers...${NC}"
PROVIDERS=(
    "Microsoft.ContainerService"
    "Microsoft.Storage"
    "Microsoft.Network"
    "Microsoft.Compute"
    "Microsoft.DBforPostgreSQL"
    "Microsoft.OperationalInsights"
)

for provider in "${PROVIDERS[@]}"; do
    set +e
    REGISTRATION_STATE=$(az provider show --namespace "$provider" --query "registrationState" -o tsv 2>/dev/null)
    PROVIDER_EXIT_CODE=$?
    set -e
    
    if [ $PROVIDER_EXIT_CODE -eq 0 ] && [ "$REGISTRATION_STATE" = "Registered" ]; then
        echo -e "${GREEN}✓${NC} $provider (already registered)"
    else
        echo -e "${YELLOW}Registering $provider...${NC}"
        set +e
        az provider register --namespace "$provider" --wait
        REGISTER_EXIT_CODE=$?
        set -e
        if [ $REGISTER_EXIT_CODE -eq 0 ]; then
            echo -e "${GREEN}✓${NC} $provider registered"
        else
            echo -e "${RED}✗${NC} Failed to register $provider (this may be normal if you don't have permissions)"
        fi
    fi
done

echo -e "${GREEN}All providers registered${NC}"

# Export variables for Terraform
echo -e "\n${YELLOW}Setting up Terraform variables...${NC}"

TFVARS_FILE="infrastructure/terraform/terraform.tfvars"
if [ -f "$TFVARS_FILE" ]; then
    echo -e "${YELLOW}Terraform variables file already exists at $TFVARS_FILE${NC}"
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}Keeping existing file${NC}"
    else
        cat > "$TFVARS_FILE" <<EOF
# CloudSound Azure Configuration
# Auto-generated by azure-setup.sh

resource_group_name = "$RESOURCE_GROUP"
location            = "$LOCATION"
project_name        = "cloudsound"
environment         = "production"

# AKS Configuration
aks_node_count     = 2
aks_node_size      = "Standard_B2s"

# PostgreSQL Configuration
postgres_admin_user = "cloudsoundadmin"
postgres_sku_name   = "B_Standard_B1ms"
postgres_storage_mb = 32768

# Enter your email for SSL certificates
admin_email = "your-email@example.com"
EOF
        echo -e "${GREEN}Terraform variables file updated${NC}"
    fi
else
    # Create directory if it doesn't exist
    mkdir -p "$(dirname "$TFVARS_FILE")"
    cat > "$TFVARS_FILE" <<EOF
# CloudSound Azure Configuration
# Auto-generated by azure-setup.sh

resource_group_name = "$RESOURCE_GROUP"
location            = "$LOCATION"
project_name        = "cloudsound"
environment         = "production"

# AKS Configuration
aks_node_count     = 2
aks_node_size      = "Standard_B2s"

# PostgreSQL Configuration
postgres_admin_user = "cloudsoundadmin"
postgres_sku_name   = "B_Standard_B1ms"
postgres_storage_mb = 32768

# Enter your email for SSL certificates
admin_email = "your-email@example.com"
EOF
    echo -e "${GREEN}Terraform variables file created at $TFVARS_FILE${NC}"
fi
echo -e "${YELLOW}Please edit this file and add your email address${NC}"

# Create service principal for GitHub Actions
echo -e "\n${YELLOW}Creating service principal for GitHub Actions...${NC}"
read -p "Do you want to create a service principal for CI/CD? (y/n): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    SUBSCRIPTION_ID=$(az account show --query id -o tsv)
    SP_NAME="github-actions-cloudsound"
    CREATE_NEW=false
    
    # Check if service principal already exists
    set +e
    EXISTING_SP=$(az ad sp list --display-name "$SP_NAME" --query "[0].appId" -o tsv 2>/dev/null)
    set -e
    
    if [ -n "$EXISTING_SP" ] && [ "$EXISTING_SP" != "null" ]; then
        echo -e "${GREEN}Service principal '$SP_NAME' already exists${NC}"
        echo -e "${YELLOW}App ID: $EXISTING_SP${NC}"
        read -p "Do you want to create a new one anyway? (y/n): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            CREATE_NEW=true
        else
            echo -e "${YELLOW}Skipping service principal creation${NC}"
            echo -e "${YELLOW}To get credentials for the existing service principal, run:${NC}"
            echo -e "${BLUE}az ad sp credential reset --id $EXISTING_SP${NC}"
        fi
    else
        CREATE_NEW=true
    fi
    
    if [ "$CREATE_NEW" = true ]; then
        echo "Creating service principal..."
        # Temporarily disable exit on error to handle permission issues gracefully
        set +e
        SP_OUTPUT=$(az ad sp create-for-rbac \
            --name "$SP_NAME" \
            --role contributor \
            --scopes "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP" \
            --sdk-auth 2>&1)
        SP_EXIT_CODE=$?
        set -e
        
        if [ $SP_EXIT_CODE -eq 0 ]; then
            echo -e "\n${GREEN}Service Principal created!${NC}"
            echo -e "${YELLOW}Add this as AZURE_CREDENTIALS secret in GitHub:${NC}\n"
            echo "$SP_OUTPUT"
            echo -e "\n${YELLOW}Save this output - you'll need it for GitHub Actions${NC}"
        else
            echo -e "\n${RED}Failed to create service principal${NC}"
            echo -e "${YELLOW}Error details:${NC}"
            echo "$SP_OUTPUT" | grep -i "error" || echo "$SP_OUTPUT"
            echo -e "\n${YELLOW}This usually means you don't have sufficient Azure AD permissions.${NC}"
            echo -e "${YELLOW}Options:${NC}"
            echo -e "1. Ask your Azure administrator to grant you 'Application Administrator' or 'Global Administrator' role"
            echo -e "2. Create the service principal manually via Azure Portal:"
            echo -e "   ${BLUE}https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade${NC}"
            echo -e "3. Use an existing service principal if you have one"
            echo -e "4. Skip this step and create it later when you have the required permissions"
            echo -e "\n${YELLOW}For more information, see:${NC}"
            echo -e "${BLUE}https://learn.microsoft.com/azure/azure-resource-manager/resource-group-create-service-principal-portal${NC}"
        fi
    fi
fi

# Summary
echo -e "\n${BLUE}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}\n"

echo -e "Next steps:"
echo -e "1. ${YELLOW}Edit infrastructure/terraform/terraform.tfvars${NC} with your email"
echo -e "2. ${YELLOW}Deploy infrastructure:${NC} cd infrastructure/terraform && terraform apply"
echo -e "3. ${YELLOW}Configure GitHub secrets:${NC} Add AZURE_CREDENTIALS, ACR credentials, etc."
echo -e "4. ${YELLOW}Build and push images:${NC} ./scripts/build-and-push-azure.sh"
echo -e "5. ${YELLOW}Deploy application:${NC} cd infrastructure/helm/cloudsound && helm install..."

echo -e "\n${GREEN}See docs/AZURE_DEPLOYMENT.md for detailed instructions${NC}\n"

